### ISSUE TITLE
Settings are not visible in the admin panel

### ISSUE THREAD

**Issue by MorrisJobke** [nextcloud/jsloader#1]
* enable the jsloader app
* go to the admin settings
* expected there should be a category "JavaScript loader" in the left sidebar
* actual: not there - so no way to configure it

@LukasReschke @nickvergessen Could one of you look into that? I guess it's because the settings are not properly configured during installation.

cc @oparoz

**Comment by mysteryHJJ** [comment]
how to install jsloader? I cant not find it in left siderbar

**Comment by nickvergessen** [comment]
You need to download https://github.com/nextcloud/jsloader/archive/master.zip
Unzip it and upload it to your server, because it is currently not available in the appstore

**Comment by mysteryHJJ** [comment]
Thank you very much. I got it
