### ISSUE TITLE
NC 17+ App Store Release

### ISSUE THREAD

**Issue by reiner-text** [nextcloud/jsloader#14]
Please provide an updated App Store release for Nextcloud 17. Thanks!

**Comment by Cellularhacker** [comment]
Yes we need this app on 17.

**Comment by pcpostar** [comment]
+1
Wold need that on 17 as well. Thank you.

**Comment by reiner-text** [comment]
> Please provide an updated App Store release for Nextcloud 17.

… and for NC 18, too.

**Comment by gentakojima** [comment]
Did anyone test this manually on Nextcloud 17? I'm holding the update because of this plugin since 17 stable release.

**Comment by netzwerch** [comment]
> Did anyone test this manually on Nextcloud 17? I'm holding the update because of this plugin since 17 stable release.

I just now did with 20.0.2.
Made a git clone in my `custom_apps` folder, ran `./occ app:enable jsloader`, dumped my plain js tracking code and the tracker's url into the settings.
Worked instantly. Nice!

**Comment by theoneandonly-vector** [comment]
I can also confirm.. this works on 20.0.7
So is there any hope to get the latest version published on the official Store?

**Comment by MorrisJobke** [comment]
Yep - the current version was released. Let me close this then.
