### ISSUE TITLE
In Nextcloud Appstore outdated

### ISSUE THREAD

**Issue by Killerhaschen** [nextcloud/jsloader#22]
In the Nextcloud Appstore the app is outdated.
https://apps.nextcloud.com/apps/jsloader
Or are there two apps ?

**Comment by theoneandonly-vector** [comment]
maybe @nickvergessen can update it? it's the same.. also this app is so simple.. I think the most updates in the future just will be updating the versioning.

**Comment by theoneandonly-vector** [comment]
@nickvergessen or is there maybe a way "we" as a community can do this (update the app on the store)?

**Comment by nickvergessen** [comment]
Only people with access to the app key can do that and i don't have access

**Comment by Killerhaschen** [comment]
So only @rullzer can update it ?

**Comment by MorrisJobke** [comment]
I just released version 1.5.0 for Nextcloud 19, 20 and 21.
