### ISSUE TITLE
Upload to app store?

### ISSUE THREAD

**Issue by nickvergessen** [nextcloud/jsloader#3]
https://github.com/nextcloud/server/issues/6705

**Comment by remytms** [comment]
Hi,

I'm also interested in having jsloader in the app store.

But for now, could you confirm that the folowing steps are the good way to install jsloader ?
* On the server go in the `nextcloud/apps` directory.
* Run `git clone https://github.com/nextcloud/jsloader.git`
* Activate the JSLoader application in Nextcloud via the web interface

Thanks

**Comment by rullzer** [comment]
https://apps.nextcloud.com/apps/jsloader
